apiVersion: v2
appVersion: 0.19.0
description: DEPRECATED Apache Druid is a high performance real-time analytics database.
name: druid
dependencies:
  - name: zookeeper
    version: 2.1.4
    repository: https://charts.helm.sh/incubator
    condition: zookeeper.enabled
  - name: mysql
    version: 1.6.4
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
version: 0.3.0
home: https://druid.apache.org/
icon: https://druid.apache.org/img/favicon.png
deprecated: true
sources:
  - https://github.com/apache/druid
keywords:
  - olap
  - database
  - analytics
